# flake8: noqa

"""
    identity-provider

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from identity_provider_rest_client.api_client import ApiClient

# import Configuration
from identity_provider_rest_client.configuration import Configuration

# import exceptions
from identity_provider_rest_client.exceptions import OpenApiException
from identity_provider_rest_client.exceptions import ApiAttributeError
from identity_provider_rest_client.exceptions import ApiTypeError
from identity_provider_rest_client.exceptions import ApiValueError
from identity_provider_rest_client.exceptions import ApiKeyError
from identity_provider_rest_client.exceptions import ApiException
